version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: todo_postgres_local
    environment:
      POSTGRES_DB: todoapp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"  # Use different port to avoid conflicts
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - todo_network

  neo4j:
    image: neo4j:5.25
    container_name: todo_neo4j_local
    environment:
      NEO4J_AUTH: neo4j/password
      NEO4J_PLUGINS: '["apoc"]'
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
    networks:
      - todo_network

  backend:
    build: ./backend
    container_name: todo_backend_local
    ports:
      - "8001:8000"  # Use different port to avoid conflicts
    environment:
      DATABASE_URL: postgresql://postgres:password@postgres:5432/todoapp
      NEO4J_URI: bolt://neo4j:7687
      NEO4J_USER: neo4j
      NEO4J_PASSWORD: password
    depends_on:
      - postgres
      - neo4j
    volumes:
      - ./backend:/app
    networks:
      - todo_network

  frontend:
    build: ./frontend
    container_name: todo_frontend_local
    ports:
      - "3001:3000"  # Use different port to avoid conflicts
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8001
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - todo_network

volumes:
  postgres_data:
  neo4j_data:
  neo4j_logs:

networks:
  todo_network:
    driver: bridge