version: '3.8'

services:
  postgres:
    image: docker.io/library/postgres:16
    container_name: todo_postgres
    environment:
      POSTGRES_DB: todoapp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  neo4j:
    image: docker.io/library/neo4j:5.25
    container_name: todo_neo4j
    environment:
      NEO4J_AUTH: neo4j/password
      NEO4J_PLUGINS: '["apoc"]'
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs

  backend:
    build: 
      context: ../../backend
      dockerfile: Dockerfile
    container_name: todo_backend
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://postgres:password@postgres:5432/todoapp
      NEO4J_URI: bolt://neo4j:7687
      NEO4J_USER: neo4j
      NEO4J_PASSWORD: password
    depends_on:
      - postgres
      - neo4j

volumes:
  postgres_data:
  neo4j_data:
  neo4j_logs: